{% set name = "lfric_reader" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/niwa/lfric_reader/archive/v{{ version }}.tar.gz
  sha256: 60e217cfae0e754d2edc383d26944857098390608c1b0a2e6d3339935ef515d1

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - make  # [unix]
    - cmake
  host:
    - paraview
    - python
    - libnetcdf
    - boost-cpp
    - eigen
    - xorg-libxfixes  # [linux]
  run:
    - paraview
    - python

test:
  commands:
    - python -c "import paraview.simple as pvs; pvs.LoadPlugin('$PREFIX/lib/netCDFLFRicReader/netCDFLFRicReader.so')"  # [not win]
    - python -c "import paraview.simple as pvs; pvs.LoadPlugin(r'%PREFIX%\Library\bin\netCDFLFRicReader\netCDFLFRicReader.dll')"  # [win]

about:
  home: https://github.com/niwa/lfric_reader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ParaView plugin that reads output from the LFRic code in netCDF UGRID format
  description: |
    ParaView plugin that reads output from the LFRic
    code in netCDF UGRID format.
  doc_url: https://github.com/niwa/lfric_reader
  dev_url: https://github.com/niwa/lfric_reader

extra:
  recipe-maintainers:
    - tinyendian
