{% set name = "lfric_reader" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/niwa/lfric_reader/archive/v{{ version }}.tar.gz
  sha256: bbcb146b5c93a9c7e541380745d890742bc89e496b6edc6cb05d411ea810995f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - cmake
  host:
    - paraview
    - python
    - libnetcdf
    - boost
    - eigen
    - xorg-libxfixes  # [linux]
  run:
    - paraview
    - python

test:
  commands:
    - python -c "import paraview.simple as pvs; pvs.LoadPlugin('$PREFIX/lib/netCDFLFRicReader/netCDFLFRicReader.so')"

about:
  home: https://github.com/niwa/lfric_reader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ParaView plugin that reads output from the LFRic code in netCDF UGRID format
  description: |
    ParaView plugin that reads output from the LFRic
    code in netCDF UGRID format.
  doc_url: https://github.com/niwa/lfric_reader
  dev_url: https://github.com/niwa/lfric_reader

extra:
  recipe-maintainers:
    - tinyendian
